### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by simon-p-r** [ide/hapi-async-handler#3]
Hi

Maybe a bit off topic but say you had to run a series of async operations within a handler, how would you achieve this with async await?

Thanks
Simon

**Comment by ide** [comment]
I'm not sure I understand your question but I'll try to answer it with an example. Say you are writing a chat app and have an endpoint for sending a message that needs to do two things: store the message in the database and send a push notification to the recipient. The code would look like:

``` js
async function storeMessage(senderId, recipientId, message) { ... }
async function sendPushNotification(senderId, recipientId, message) { ... }

server.route({
  method: 'POST',
  path: '/send-message',
  handler: {
    async: async function(request, reply) {
      var senderId = request.params.userId;
      var recipientId = request.params.recipientId;
      var message = request.params.message;
      // These two async operations don't depend on one another so we can run them
      // concurrently using Promise.all.
      await Promise.all([
        storeMessage(senderId, recipientId, message),
        sendPushNotification(senderId, recipientId, message),
      ]);
      reply('success');
    }
  }
});
```

Now if you have two async operations that do depend on one another, you write two `await` expressions:

``` js
/**
 * Sends a push notification to the recipient, notifying them that the sender
 * has sent them a message.
 */
async function sendPushNotification(senderId, recipientId, message) {
  var senderProfile = await fetchUserProfile(senderId);
  var notificationText = senderProfile.name + ' says: ' + message;
  await PushNotificationService.sendNotification(recipientId, notificationText);
}
```

This first fetches the profile of the person sending the message so their name can be included in the notification text. After the database fetch asynchronously completes, the rest of the function runs.

There is also a potential optimization here. Since the function ends with an `await` expression statement, you can write:

``` js
async function sendPushNotification(senderId, recipientId, message) {
  var senderProfile = await fetchUserProfile(senderId);
  var notificationText = senderProfile.name + ' says: ' + message;
  // Avoid one unnecessary continuation of this function
  return PushNotificationService.sendNotification(recipientId, notificationText);
}
```

This reduces the number of times the JS interpreter needs to step in and out of the async function.

**Comment by simon-p-r** [comment]
Ok thanks for the extensive answer.  How do I transform the source code to make use of the async keyword?

**Comment by ide** [comment]
Take a look at a project called Babel. It's quite active and there should be some convenient gulp or grunt scripts to help you get set up.

**Comment by simon-p-r** [comment]
OK thanks
